### ISSUE TITLE
Nonstatic JNI doesn't work

### ISSUE THREAD

**Issue by ninja-gaiden** [shoebox/inthebox-macros#12]
I'm using HypFacebook lib in my project which depends on inthebox-macros. All static JNI calls work, but calling any nonstatic method like 'connect' crashes application with this error: 

<pre>
06-30 19:33:22.443: W/System.err(30219): java.lang.NoSuchMethodError: no method with name='connect' signature='(Lorg/haxe/lime/HaxeObject;Z)Z' in class Lfr/hyperfiction/HypFacebook;
06-30 19:33:22.448: W/System.err(30219): 	at org.haxe.lime.Lime.onResize(Native Method)
06-30 19:33:22.448: W/System.err(30219): 	at org.haxe.lime.MainView$Renderer.onSurfaceChanged(MainView.java:714)
06-30 19:33:22.448: W/System.err(30219): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
06-30 19:33:22.448: W/System.err(30219): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
06-30 19:33:22.453: I/trace(30219): Lib.hx:300: JNI Exception
06-30 19:33:22.453: I/trace(30219): Called from *._Function_1_1 (ApplicationMain.hx line 77)
06-30 19:33:22.453: I/trace(30219): Called from Reflect.callMethod (C:\Haxe\haxe\std/cpp/_std/Reflect.hx line 50)
06-30 19:33:22.453: I/trace(30219): Called from com.agent.facebookexample.Main.main (com/agent/facebookexample/Main.hx line 76)
06-30 19:33:22.453: I/trace(30219): Called from flash.display.DisplayObjectContainer.addChild (flash/display/DisplayObjectContainer.hx line 31)
06-30 19:33:22.453: I/trace(30219): Called from flash.display.DisplayObject.__setParent (flash/display/DisplayObject.hx line 429)
06-30 19:33:22.453: I/trace(30219): Called from flash.display.DisplayObjectContainer.__onAdded (flash/display/DisplayObjectContainer.hx line 373)
06-30 19:33:22.453: I/trace(30219): Called from flash.display.DisplayObject.__onAdded (flash/display/DisplayObject.hx line 370)
06-30 19:33:22.453: I/trace(30219): Called from flash.display.DisplayObject.dispatchEvent (flash/display/DisplayObject.hx line 70)
06-30 19:33:22.453: I/trace(30219): Called from flash.display.DisplayObject.__dispatchEvent (flash/display/DisplayObject.hx line 193)
06-30 19:33:22.453: I/trace(30219): Called from flash.events.EventDispatcher.dispatchEvent (flash/events/EventDispatcher.hx line 98)
06-30 19:33:22.453: I/trace(30219): Called from flash.events.Listener.dispatchEvent (flash/events/EventDispatche
</pre>

I see that it expects a method with signature "(Lorg/haxe/lime/HaxeObject;Z)Z" as Haxe call from HypFacebook.hx is:
<pre lang="javascript">
@JNI("fr.hyperfiction.HypFacebook","connect")
public function jni_connect( instance:Dynamic, allowUI : Bool ) : Bool
</pre>

But in HypFacebook.java we have:
<pre lang="java">
public boolean connect( boolean allowUI )
</pre>

And if to match signatures I change it to:
<pre lang="java">
public boolean connect( HaxeObject object, boolean allowUI )
</pre>
method is called without aforementioned crash, but different problem occurs (seen in trace):
<pre>
07-01 12:21:26.969: E/NME(18188): Invalid array count: 1!=1642277064
07-01 12:21:26.969: E/NME(18188): CallMember - bad argument list
</pre>

Supposably that macro thing is not working correctly for me, maybe something is wrong with my haxe build?

<pre>
Haxe Compiler 3.1.3
actuate: 1.52 1.6.3 1.7.1 1.7.2 [1.7.5]
format: 3.0.4 [3.0.5]
haxelib_client: [3.1.0-rc.4]
hxcpp: 2.10.3 3.0.2 3.1.30 [3.1.39]
hxlibc: 1.1.1 [1.1.4]
hxtools: [1.1.6]
inthebox-macros: [1.1.0]
lime-tools: 1.2.2 1.4.0 [1.5.7]
lime: 0.9.0 0.9.7 [1.0.1]
nme: 4.0.2 5.0.37 [5.1.8]
openfl-compatibility: [1.0.1]
openfl-html5: 1.0.1 1.0.2 1.0.5 [1.4.2-beta]
openfl-native: 1.0.1 1.2.0 [1.4.0]
openfl-samples: 1.0.0-rc.1 1.2.0 [1.3.0]
openfl-tools: 1.0.0 [1.0.10] 1.0.2
openfl: 1.0.1 1.0.4 1.0.5 1.2.0 1.2.1 1.2.2 [1.4.0] 2.0.1
svg: 1.0.7 [1.0.8] 1.04
swf: 1.0.0 1.0.1 1.0.2 1.17 1.2.0 1.4.2 [1.5.2]
</pre>

Thanks.

**Comment by shoebox** [comment]
cf : https://github.com/shoebox/inthebox-macros/pull/17
